openapi: 3.2.0
info:
  title: YOOBIC Public Notifications API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Notifications
  description: Notifications provide information about the internal notifications sent to users in the application.
paths:
  /public/api/notifications/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  notification_id:
                    type: string
                  title:
                    type: string
                  mode:
                    type: string
                  sender_id:
                    type: string
                  push_recipients:
                    type: number
                  entity_type:
                    type: string
                  entity_id:
                    type: string
                  updated_date:
                    type: string
                  created_date:
                    type: string
                example:
                  notification_id: 54ab03c6546847ee0d30081d
                  title: Rocket ltd notification 1
                  mode: notification
                  sender_id: 54ab03c6546847ee0d30072b
                  push_recipients: 3
                  entity_type: Mission
                  entity_id: 54ab03c6546847ee0d30072a
                  updated_date: '2018-05-23T04:51:40.862Z'
                  created_date: '2018-05-23T04:51:40.862Z'
              examples:
                response:
                  value:
                    notification_id: 54ab03c6546847ee0d30081d
                    title: Rocket ltd notification 1
                    mode: notification
                    sender_id: 54ab03c6546847ee0d30072b
                    push_recipients: 3
                    entity_type: Mission
                    entity_id: 54ab03c6546847ee0d30072a
                    updated_date: '2018-05-23T04:51:40.862Z'
                    created_date: '2018-05-23T04:51:40.862Z'
      summary: Get
      operationId: Get
      description: Get a notification for the given id.
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        description: The id of the notification
        required: true
        example: 54ab03c6546847ee0d30083e
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/notifications?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    notification_id:
                      type: string
                    title:
                      type: string
                    mode:
                      type: string
                    sender_id:
                      type: string
                    push_recipients:
                      oneOf:
                      - type: number
                      - type: string
                    entity_type:
                      type: string
                    entity_id:
                      type: string
                    updated_date:
                      type: string
                    created_date:
                      type: string
                  required:
                  - notification_id
                  - title
                  - mode
                  - sender_id
                  - push_recipients
                  - entity_type
                  - entity_id
                  - updated_date
                  - created_date
                example:
                - notification_id: 54ab03c6546847ee0d30081d
                  title: Rocket ltd notification 1
                  mode: notification
                  sender_id: 54ab03c6546847ee0d30072b
                  push_recipients: 3
                  entity_type: Mission
                  entity_id: 54ab03c6546847ee0d30072a
                  updated_date: '2018-05-23T04:51:40.862Z'
                  created_date: '2018-05-23T04:51:40.862Z'
                - notification_id: 54ab03c6546847ee0d30081e
                  title: Rocket ltd notification 2
                  mode: notification
                  sender_id: 54ab03c6546847ee0d30072b
                  push_recipients: '1'
                  entity_type: Mission
                  entity_id: 54ab03c6546847ee0d30072a
                  updated_date: '2018-05-23T04:51:40.862Z'
                  created_date: '2018-05-23T04:51:40.862Z'
              examples:
                response:
                  value:
                  - notification_id: 54ab03c6546847ee0d30081d
                    title: Rocket ltd notification 1
                    mode: notification
                    sender_id: 54ab03c6546847ee0d30072b
                    push_recipients: 3
                    entity_type: Mission
                    entity_id: 54ab03c6546847ee0d30072a
                    updated_date: '2018-05-23T04:51:40.862Z'
                    created_date: '2018-05-23T04:51:40.862Z'
                  - notification_id: 54ab03c6546847ee0d30081e
                    title: Rocket ltd notification 2
                    mode: notification
                    sender_id: 54ab03c6546847ee0d30072b
                    push_recipients: '1'
                    entity_type: Mission
                    entity_id: 54ab03c6546847ee0d30072a
                    updated_date: '2018-05-23T04:51:40.862Z'
                    created_date: '2018-05-23T04:51:40.862Z'
      summary: Get All
      operationId: Get All
      description: Get all the notifications.
      tags:
      - Notifications
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/notifications:
    post:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Create
      operationId: Create
      description: 'You may create a new single notification or multiple notifications using this action.

        When creating a single notification the body contains a json object, when creating multiple notifications the body contains an array of objects.

        **Warning: a maximum of 1000 items can be sent in a single request.**'
      tags:
      - Notifications
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_ids:
                  type: array
                  items:
                    type: string
                group_ids:
                  type: array
                  items:
                    type: string
                title:
                  type: string
                body:
                  type: string
                mode:
                  type: string
                entity_type:
                  type: string
                entity_id:
                  type: string
              example:
                user_ids:
                - 5babb8a69fa6ae919f675715
                - 5babb8a69fa6ae919f675716
                group_ids:
                - company_employees
                title: Major news
                body: New deal signed with ...
                mode: push
                entity_type: news
                entity_id: 54ab03c6546847ee0d30084a
      security:
      - oauth2: []
  /public/api/notifications/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Notifications
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/notifications/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Notifications
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
