openapi: 3.2.0
info:
  title: YOOBIC Public Answers API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Answers
  description: Answers are the users’ replies to the questions raised by their colleagues in the Questions menu.
paths:
  /public/api/answers/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer_id:
                    type: string
                  question_id:
                    type: string
                  user_id:
                    type: string
                  text:
                    type: string
                  likes:
                    type: number
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  answer_id: 63459c260a1b6d001dc60f8e
                  question_id: 6343ee166c8a0e001de9bd7f
                  user_id: 5e272f12e1d5f2003ad7afe6
                  text: Comment
                  likes: 1
                  created_date: '2022-10-11T16:39:02.900Z'
                  updated_date: '2022-10-11T16:41:28.566Z'
              examples:
                response:
                  value:
                    answer_id: 63459c260a1b6d001dc60f8e
                    question_id: 6343ee166c8a0e001de9bd7f
                    user_id: 5e272f12e1d5f2003ad7afe6
                    text: Comment
                    likes: 1
                    created_date: '2022-10-11T16:39:02.900Z'
                    updated_date: '2022-10-11T16:41:28.566Z'
      summary: Get
      operationId: Get
      description: Get a answer for the given id.
      tags:
      - Answers
      parameters:
      - name: id
        in: path
        description: The id of the answer
        required: true
        example: 61b9b435c8f864003a552378
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/answers?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      skip:
                        type: number
                      limit:
                        type: number
                      total:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        answer_id:
                          type: string
                        question_id:
                          type: string
                        user_id:
                          type: string
                        text:
                          type: string
                        likes:
                          type: number
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - answer_id
                      - question_id
                      - user_id
                      - text
                      - likes
                      - created_date
                      - updated_date
                example:
                  paging:
                    skip: 0
                    limit: 3
                    total: 2000
                  data:
                  - answer_id: 63459c260a1b6d001dc60f8e
                    question_id: 6343ee166c8a0e001de9bd7f
                    user_id: 5e272f12e1d5f2003ad7afe6
                    text: Comment
                    likes: 1
                    created_date: '2022-10-11T16:39:02.900Z'
                    updated_date: '2022-10-11T16:41:28.566Z'
                  - answer_id: 63459c679693060027345b91
                    question_id: 6343ee166c8a0e001de9bd7f
                    user_id: 5e1356f0c5f0e0003d305072
                    text: Comm
                    likes: 10
                    created_date: '2022-10-11T16:40:07.994Z'
                    updated_date: '2022-10-11T16:40:16.175Z'
                  - answer_id: 63459b240a1b6d001dc60c48
                    question_id: 63453bd184b108002a5166ae
                    user_id: 5e1356f0c5f0e0003d305072
                    text: '@Hq2 mention from web'
                    created_date: '2022-10-11T16:34:44.892Z'
                    updated_date: '2022-10-11T16:34:44.892Z'
              examples:
                response:
                  value:
                    paging:
                      skip: 0
                      limit: 3
                      total: 2000
                    data:
                    - answer_id: 63459c260a1b6d001dc60f8e
                      question_id: 6343ee166c8a0e001de9bd7f
                      user_id: 5e272f12e1d5f2003ad7afe6
                      text: Comment
                      likes: 1
                      created_date: '2022-10-11T16:39:02.900Z'
                      updated_date: '2022-10-11T16:41:28.566Z'
                    - answer_id: 63459c679693060027345b91
                      question_id: 6343ee166c8a0e001de9bd7f
                      user_id: 5e1356f0c5f0e0003d305072
                      text: Comm
                      likes: 10
                      created_date: '2022-10-11T16:40:07.994Z'
                      updated_date: '2022-10-11T16:40:16.175Z'
                    - answer_id: 63459b240a1b6d001dc60c48
                      question_id: 63453bd184b108002a5166ae
                      user_id: 5e1356f0c5f0e0003d305072
                      text: '@Hq2 mention from web'
                      created_date: '2022-10-11T16:34:44.892Z'
                      updated_date: '2022-10-11T16:34:44.892Z'
      summary: Get All
      operationId: Get All
      description: Get all the answers.
      tags:
      - Answers
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/answers/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Answers
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/answers/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Answers
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
