openapi: 3.2.0
info:
  title: YOOBIC Public Webhooks API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Webhooks
  description: You can create webhooks with HTTP targets to build integrations with the services or with your back-end system.
paths:
  /public/api/webhooks/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook_id:
                    type: string
                  url:
                    type: string
                  topics:
                    type: array
                    items:
                      type: string
                  operations:
                    type: array
                    items:
                      type: string
                  is_active:
                    type: boolean
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  webhook_id: 5ea689b6bd436e37567caffe
                  url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                  topics:
                  - stores
                  - store-types
                  - users
                  - missions
                  - campaigns
                  operations:
                  - create
                  - update
                  - delete
                  is_active: true
                  created_date: '2020-04-27T07:28:54.324Z'
                  updated_date: '2020-04-27T07:28:54.324Z'
              examples:
                response:
                  value:
                    webhook_id: 5ea689b6bd436e37567caffe
                    url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                    topics:
                    - stores
                    - store-types
                    - users
                    - missions
                    - campaigns
                    operations:
                    - create
                    - update
                    - delete
                    is_active: true
                    created_date: '2020-04-27T07:28:54.324Z'
                    updated_date: '2020-04-27T07:28:54.324Z'
      summary: Get
      operationId: Get
      description: Get a webhook for the given id
      tags:
      - Webhooks
      parameters:
      - name: id
        in: path
        description: The id of the webhooks
        required: true
        example: 5efd1157b2e93c96bc8ea071
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook_id:
                    type: string
                  url:
                    type: string
                  topics:
                    type: array
                    items:
                      type: string
                  is_active:
                    type: boolean
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  webhook_id: 5ea689b6bd436e37567caffe
                  url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                  topics:
                  - stores
                  - store-types
                  - users
                  - missions
                  - campaigns
                  is_active: false
                  created_date: '2020-04-27T07:28:54.324Z'
                  updated_date: '2020-04-27T07:28:54.324Z'
              examples:
                response:
                  value:
                    webhook_id: 5ea689b6bd436e37567caffe
                    url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                    topics:
                    - stores
                    - store-types
                    - users
                    - missions
                    - campaigns
                    is_active: false
                    created_date: '2020-04-27T07:28:54.324Z'
                    updated_date: '2020-04-27T07:28:54.324Z'
      summary: Partial Update
      operationId: Partial Update
      description: Update a subset of properties of a webhook
      tags:
      - Webhooks
      parameters:
      - name: id
        in: path
        description: The id of the webhooks
        required: true
        example: 5efd1157b2e93c96bc8ea071
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                is_active:
                  type: boolean
              example:
                is_active: false
      security:
      - oauth2: []
  /public/api/webhooks?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    webhook_id:
                      type: string
                    url:
                      type: string
                    topics:
                      type: array
                      items:
                        type: string
                    is_active:
                      type: boolean
                    created_date:
                      type: string
                    updated_date:
                      type: string
                  required:
                  - webhook_id
                  - url
                  - topics
                  - is_active
                  - created_date
                  - updated_date
                example:
                - webhook_id: 5ea689b6bd436e37567caffe
                  url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                  topics:
                  - missions
                  is_active: true
                  created_date: '2020-04-27T07:28:54.324Z'
                  updated_date: '2020-04-27T07:28:54.324Z'
                - webhook_id: 5ea689b6bd436e37567caffe
                  url: https://webhook.site/b258e106-5bb3-4b96-9ebf-a942743244a9
                  topics:
                  - stores
                  is_active: true
                  created_date: '2020-04-27T07:28:54.324Z'
                  updated_date: '2020-04-27T07:28:54.324Z'
              examples:
                response:
                  value:
                  - webhook_id: 5ea689b6bd436e37567caffe
                    url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                    topics:
                    - missions
                    is_active: true
                    created_date: '2020-04-27T07:28:54.324Z'
                    updated_date: '2020-04-27T07:28:54.324Z'
                  - webhook_id: 5ea689b6bd436e37567caffe
                    url: https://webhook.site/b258e106-5bb3-4b96-9ebf-a942743244a9
                    topics:
                    - stores
                    is_active: true
                    created_date: '2020-04-27T07:28:54.324Z'
                    updated_date: '2020-04-27T07:28:54.324Z'
      summary: Get All
      operationId: Get All
      description: Get all the webhooks.
      tags:
      - Webhooks
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/webhooks:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook_id:
                    type: string
                  url:
                    type: string
                  topics:
                    type: array
                    items:
                      type: string
                  operations:
                    type: array
                    items:
                      type: string
                  is_active:
                    type: boolean
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  webhook_id: 5ea689b6bd436e37567caffe
                  url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                  topics:
                  - missions
                  operations:
                  - create
                  is_active: true
                  created_date: '2020-04-27T07:28:54.324Z'
                  updated_date: '2020-04-27T07:28:54.324Z'
              examples:
                response:
                  value:
                    webhook_id: 5ea689b6bd436e37567caffe
                    url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                    topics:
                    - missions
                    operations:
                    - create
                    is_active: true
                    created_date: '2020-04-27T07:28:54.324Z'
                    updated_date: '2020-04-27T07:28:54.324Z'
      summary: Create
      operationId: Create
      description: 'Creating webhooks.


        - note: The body can accept a `filter` for the webhook based on the chosen topic. The `filter` can be about any filterable property of the objects from this topic (example: `campaign_id` for topic `missions`)'
      tags:
      - Webhooks
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                topics:
                  type: array
                  items:
                    type: string
                operations:
                  type: array
                  items:
                    type: string
                filter:
                  type: object
                  properties:
                    campaign_id:
                      type: string
              example:
                url: https://webhook.site/b258e106-5aa3-4b86-9eef-a942643243a8
                topics:
                - missions
                operations:
                - create
                filter:
                  campaign_id: 6548ec4dee43840028a59a56
      security:
      - oauth2: []
  /public/api/webhooks/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Webhooks
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/webhooks/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Webhooks
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/webhooks/import?type={type}:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Import file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Import file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Import
      operationId: Import
      description: See the Import file section for more information.
      tags:
      - Webhooks
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: Content-Disposition
        in: header
        description: e.g. form-data; name="file"; filename="file.csv"
        required: false
        example: form-data; name="file"; filename="file.csv"
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ImportBody'
components:
  requestBodies:
    ImportBody:
      content:
        multipart/form-data, boundary=AaB03x:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
