openapi: 3.2.0
info:
  title: YOOBIC Public Translations API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Translations
  description: Contains translations of common keys used in the app to different languages.
paths:
  /public/api/translations/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  translation_id:
                    type: string
                  language:
                    type: string
                  key:
                    type: string
                  value:
                    type: string
                  us:
                    type: string
                  en:
                    type: string
                  ca:
                    type: string
                  fr:
                    type: string
                  de:
                    type: string
                  es:
                    type: string
                  nl:
                    type: string
                  pl:
                    type: string
                  it:
                    type: string
                  ru:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                  group_ids:
                    type: array
                    items:
                      type: string
                example:
                  translation_id: 587de6c4e000eb001877e3a1
                  language: fr
                  key: ACTIONPLANCAMPAIGNDESCRIPTION
                  value: Faites le tour du magasin avec cette fiche de visite
                  us: Walk around the store with the visit sheet
                  en: Walk around the store with the visit sheet
                  ca: Walk around the store with the visit sheet
                  fr: Faites le tour du magasin avec cette fiche de visite
                  de: Gehen Sie um den Laden mit dem Besuch Blatt
                  es: Paseo por la tienda con la hoja de visita
                  nl: Loop rond de winkel met het bezoek vel
                  pl: Spacer po sklepie z arkuszem wizyty
                  it: Passeggiata intorno al negozio con la scheda di visita
                  ru: Прогулка вокруг магазина с посещением листа
                  created_date: '2017-01-17T09:41:24.401Z'
                  updated_date: '2017-01-18T15:27:49.026Z'
                  group_ids:
                  - yoobicprojectmanager
              examples:
                response:
                  value:
                    translation_id: 587de6c4e000eb001877e3a1
                    language: fr
                    key: ACTIONPLANCAMPAIGNDESCRIPTION
                    value: Faites le tour du magasin avec cette fiche de visite
                    us: Walk around the store with the visit sheet
                    en: Walk around the store with the visit sheet
                    ca: Walk around the store with the visit sheet
                    fr: Faites le tour du magasin avec cette fiche de visite
                    de: Gehen Sie um den Laden mit dem Besuch Blatt
                    es: Paseo por la tienda con la hoja de visita
                    nl: Loop rond de winkel met het bezoek vel
                    pl: Spacer po sklepie z arkuszem wizyty
                    it: Passeggiata intorno al negozio con la scheda di visita
                    ru: Прогулка вокруг магазина с посещением листа
                    created_date: '2017-01-17T09:41:24.401Z'
                    updated_date: '2017-01-18T15:27:49.026Z'
                    group_ids:
                    - yoobicprojectmanager
      summary: Get
      operationId: Get
      description: Get a translation for the given id.
      tags:
      - Translations
      parameters:
      - name: id
        in: path
        description: The id of the translation
        required: true
        example: 54ab03c6546847ee0d30083e
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
      summary: Delete
      operationId: Delete
      description: Delete a translation by id.
      tags:
      - Translations
      parameters:
      - name: id
        in: path
        description: The id of the translation
        required: true
        example: 54ab03c6546847ee0d30083e
        schema:
          type: string
      security:
      - oauth2: []
    patch:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Partial Update
      operationId: Partial Update
      description: Update a subset of properties of a translation
      tags:
      - Translations
      parameters:
      - name: id
        in: path
        description: The id of the translation
        required: true
        example: 54ab03c6546847ee0d30083e
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pr:
                  type: string
                ru:
                  type: string
              example:
                pr: personalizado
                ru: обычай
      security:
      - oauth2: []
  /public/api/translations?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Get All
      operationId: Get All
      description: Get all the translations.
      tags:
      - Translations
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/translations:
    post:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Create
      operationId: Create
      description: 'You may create a new single translation or multiple translations using this action.

        When creating a single translation the body contains a json object, when creating multiple translations the body contains an array of objects.

        **Warning: a maximum of 1000 items can be sent in a single request.**'
      tags:
      - Translations
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/translations/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Translations
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/translations/export?filter={filter}&type={type}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Translations
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/translations/import?type={type}:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Import file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Import file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Import
      operationId: Import
      description: 'See the Import file section for more information.


        ### Fields


        | Column | Format | Required | Description |

        |----------------------|-------------|-----------|----------------|

        |`translation_id` | string | | Unique id of the translations |

        |`language` | string | x | Default language chosen for the key |

        |`key` | string | x | The key that references this translation |

        |`value` | string | x | Translated key by the default language |

        |`group_ids` | array | x | Group ids that can see these translations |

        |`us` | string | | English - United States |

        |`en` | string | | English |

        |`ca` | string | | English - Canada |

        |`fr` | string | | French |

        |`de` | string | | German |

        |`es` | string | | Spanish |

        |`nl` | string | | Dutch |

        |`pl` | string | | Polish |

        |`it` | string | | Italian |

        |`ru` | string | | Russian |

        |`zhs` | string | | Simplified Chinese |

        |`zht` | string | | Traditional Chinese |

        |`pt` | string | | Portuguese |

        |`kr` | string | | Kanuri |

        |`ja` | string | | Japanese |

        |`ua` | string | | Ukrainian |

        |`he` | string | | Hebrew |

        |`ar` | string | | Arabic |

        |`cz` | string | | Czech |

        |`th` | string | | Thai |

        |`tr` | string | | Turkish |

        |`bg` | string | | Bulgarian |

        |`el` | string | | Greek |

        |`sl` | string | | Slovanian |

        |`sk` | string | | Slovak |

        |`ro` | string | | Romanian |

        |`hu` | string | | Hungarian |

        |`br` | string | | Brazilian Portuguese |

        |`et` | string | | Estonian |

        |`au` | string | | Australian |

        |`ido` | string | | Indonesian |

        |`vi` | string | | Vietnamese |

        |`da` | string | | Danish |

        |`fi` | string | | Finnish |

        |`nb` | string | | Norwegian |

        |`sv` | string | | Swedish |

        |`base_language` | string | | the base language code of the plan |

        |`updated_date` | date | | translations item last update date|

        |`created_date` | date | | translations item creation date |'
      tags:
      - Translations
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: Content-Disposition
        in: header
        description: e.g. form-data; name="file"; filename="file.csv"
        required: false
        example: form-data; name="file"; filename="file.csv"
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ImportBody'
components:
  requestBodies:
    ImportBody:
      content:
        multipart/form-data, boundary=AaB03x:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
