openapi: 3.2.0
info:
  title: YOOBIC Public Files API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Files
  description: Files provides information about the external files used in the application.
paths:
  /public/api/files/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_id:
                    type: string
                  folder_id:
                    type: string
                  folder_name:
                    type: string
                  size:
                    type: number
                  filename:
                    type: string
                  download_url:
                    type: string
                  mime_type:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  file_id: 54ab03c6546847ee0d30087d
                  folder_id: 54ab03c6546847ee0d30087b
                  folder_name: Rockets folder
                  size: 25
                  filename: Rockets file 1
                  download_url: www.rocketltd.com/file/RocketsFile1.jpg
                  mime_type: jpg
                  created_date: '2018-05-23T04:51:40.862Z'
                  updated_date: '2018-05-23T04:51:40.862Z'
              examples:
                response:
                  value:
                    file_id: 54ab03c6546847ee0d30087d
                    folder_id: 54ab03c6546847ee0d30087b
                    folder_name: Rockets folder
                    size: 25
                    filename: Rockets file 1
                    download_url: www.rocketltd.com/file/RocketsFile1.jpg
                    mime_type: jpg
                    created_date: '2018-05-23T04:51:40.862Z'
                    updated_date: '2018-05-23T04:51:40.862Z'
      summary: Get
      operationId: Get
      description: Get a file for the given id.
      tags:
      - Files
      parameters:
      - name: id
        in: path
        description: The id of the file
        required: true
        example: 54ab03c6546847ee0d30087d
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/files:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_id:
                    type: string
                  folder_id:
                    type: string
                  folder_name:
                    type: string
                  size:
                    type: number
                  filename:
                    type: string
                  download_url:
                    type: string
                  mime_type:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  file_id: 54ab03c6546847ee0d30087d
                  folder_id: 54ab03c6546847ee0d30087b
                  folder_name: Rockets folder
                  size: 25
                  filename: Rockets file 1
                  download_url: www.rocketltd.com/file/RocketsFile1.jpg
                  mime_type: jpg
                  created_date: '2018-05-23T04:51:40.862Z'
                  updated_date: '2018-05-23T04:51:40.862Z'
              examples:
                response:
                  value:
                    file_id: 54ab03c6546847ee0d30087d
                    folder_id: 54ab03c6546847ee0d30087b
                    folder_name: Rockets folder
                    size: 25
                    filename: Rockets file 1
                    download_url: www.rocketltd.com/file/RocketsFile1.jpg
                    mime_type: jpg
                    created_date: '2018-05-23T04:51:40.862Z'
                    updated_date: '2018-05-23T04:51:40.862Z'
      summary: Create
      operationId: Create
      description: 'Upload a file in YOOBIC Documents.


        To upload a photo, you should make a post request of type multipart/form-data. The request body should contain two fields:


        - `file`: the binary file you want to upload.


        - `group_ids`: select the groups that will have visibility of the file.


        - Optionally, `folder_id`: select the parent folder to upload the file.'
      tags:
      - Files
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/files?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    file_id:
                      type: string
                    folder_id:
                      type: string
                    folder_name:
                      type: string
                    size:
                      type: number
                    filename:
                      type: string
                    download_url:
                      type: string
                    mime_type:
                      type: string
                    created_date:
                      type: string
                    updated_date:
                      type: string
                  required:
                  - file_id
                  - folder_id
                  - folder_name
                  - size
                  - filename
                  - download_url
                  - mime_type
                  - created_date
                  - updated_date
                example:
                - file_id: 54ab03c6546847ee0d30087d
                  folder_id: 54ab03c6546847ee0d30087b
                  folder_name: Rockets folder
                  size: 25
                  filename: Rockets file 1
                  download_url: www.rocketltd.com/file/RocketsFile1.jpg
                  mime_type: jpg
                  created_date: '2018-05-23T04:51:40.862Z'
                  updated_date: '2018-05-23T04:51:40.862Z'
                - file_id: 54ab03c6546847ee0d30087e
                  folder_id: 54ab03c6546847ee0d30087b
                  folder_name: Rockets folder
                  size: 25
                  filename: Rockets file 2
                  download_url: www.rocketltd.com/file/RocketsFile2.jpg
                  mime_type: jpg
                  created_date: '2018-05-23T04:51:40.862Z'
                  updated_date: '2018-05-23T04:51:40.862Z'
              examples:
                response:
                  value:
                  - file_id: 54ab03c6546847ee0d30087d
                    folder_id: 54ab03c6546847ee0d30087b
                    folder_name: Rockets folder
                    size: 25
                    filename: Rockets file 1
                    download_url: www.rocketltd.com/file/RocketsFile1.jpg
                    mime_type: jpg
                    created_date: '2018-05-23T04:51:40.862Z'
                    updated_date: '2018-05-23T04:51:40.862Z'
                  - file_id: 54ab03c6546847ee0d30087e
                    folder_id: 54ab03c6546847ee0d30087b
                    folder_name: Rockets folder
                    size: 25
                    filename: Rockets file 2
                    download_url: www.rocketltd.com/file/RocketsFile2.jpg
                    mime_type: jpg
                    created_date: '2018-05-23T04:51:40.862Z'
                    updated_date: '2018-05-23T04:51:40.862Z'
      summary: Get All
      operationId: Get All
      description: Get all the files.
      tags:
      - Files
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/files/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Files
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/files/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Files
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
