openapi: 3.2.0
info:
  title: YOOBIC Public Comments API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Comments
  description: Get all feeds comments.
paths:
  /public/api/comments/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: string
                  user_id:
                    type: string
                  news_id:
                    type: string
                  date:
                    type: string
                  text:
                    type: string
                  text_en:
                    type: string
                  sentiment:
                    type: number
                  language:
                    type: string
                  _lmt:
                    type: string
                  _ect:
                    type: string
                  tenant:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  comment_id: 5d31ecba11e695003a9b1dfc
                  user_id: 5beee5197fc4d50043801bd1
                  news_id: 5d31b71a1a76e9003afd621e
                  date: '2019-07-19T16:15:54.554Z'
                  text: La vie est belle!
                  text_en: Life is beautiful!
                  sentiment: 0.9
                  language: fr
                  _lmt: '2019-07-19T16:15:54.610Z'
                  _ect: '2019-07-19T16:15:54.610Z'
                  tenant: tenant name
                  created_date: '2019-07-19T16:15:54.610Z'
                  updated_date: '2019-07-19T16:15:54.610Z'
              examples:
                response:
                  value:
                    comment_id: 5d31ecba11e695003a9b1dfc
                    user_id: 5beee5197fc4d50043801bd1
                    news_id: 5d31b71a1a76e9003afd621e
                    date: '2019-07-19T16:15:54.554Z'
                    text: La vie est belle!
                    text_en: Life is beautiful!
                    sentiment: 0.9
                    language: fr
                    _lmt: '2019-07-19T16:15:54.610Z'
                    _ect: '2019-07-19T16:15:54.610Z'
                    tenant: tenant name
                    created_date: '2019-07-19T16:15:54.610Z'
                    updated_date: '2019-07-19T16:15:54.610Z'
      summary: Get
      operationId: Get
      description: Get a comment for the given id.
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        description: The id of the comment
        required: true
        example: 5c6e7bd9d6313e003a5b73e1
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/comments?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        comment_id:
                          type: string
                        user_id:
                          type: string
                        news_id:
                          type: string
                        date:
                          type: string
                        text:
                          type: string
                        text_en:
                          type: string
                        language:
                          type: string
                        _lmt:
                          type: string
                        _ect:
                          type: string
                        tenant:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                        sentiment:
                          type: number
                      required:
                      - comment_id
                      - user_id
                      - news_id
                      - date
                      - text
                      - text_en
                      - language
                      - _lmt
                      - _ect
                      - tenant
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - comment_id: 5d31ecba11e695003a9b1dfc
                    user_id: 5beee5197fc4d50043801bd1
                    news_id: 5d31b71a1a76e9003afd621e
                    date: '2019-07-19T16:15:54.554Z'
                    text: Hello
                    text_en: Hello
                    language: en
                    _lmt: '2019-07-19T16:15:54.610Z'
                    _ect: '2019-07-19T16:15:54.610Z'
                    tenant: testproductv6_boost
                    created_date: '2019-07-19T16:15:54.610Z'
                    updated_date: '2019-07-19T16:15:54.610Z'
                  - comment_id: 5d31ecba11e695003a9b1dfc
                    user_id: 5beee5197fc4d50043801bd1
                    news_id: 5d31b71a1a76e9003afd621e
                    date: '2019-07-19T16:15:54.554Z'
                    text: La vie est belle!
                    text_en: Life is beautiful!
                    sentiment: 0.9
                    language: fr
                    _lmt: '2019-07-19T16:15:54.610Z'
                    _ect: '2019-07-19T16:15:54.610Z'
                    tenant: tenant name
                    created_date: '2019-07-19T16:15:54.610Z'
                    updated_date: '2019-07-19T16:15:54.610Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - comment_id: 5d31ecba11e695003a9b1dfc
                      user_id: 5beee5197fc4d50043801bd1
                      news_id: 5d31b71a1a76e9003afd621e
                      date: '2019-07-19T16:15:54.554Z'
                      text: Hello
                      text_en: Hello
                      language: en
                      _lmt: '2019-07-19T16:15:54.610Z'
                      _ect: '2019-07-19T16:15:54.610Z'
                      tenant: testproductv6_boost
                      created_date: '2019-07-19T16:15:54.610Z'
                      updated_date: '2019-07-19T16:15:54.610Z'
                    - comment_id: 5d31ecba11e695003a9b1dfc
                      user_id: 5beee5197fc4d50043801bd1
                      news_id: 5d31b71a1a76e9003afd621e
                      date: '2019-07-19T16:15:54.554Z'
                      text: La vie est belle!
                      text_en: Life is beautiful!
                      sentiment: 0.9
                      language: fr
                      _lmt: '2019-07-19T16:15:54.610Z'
                      _ect: '2019-07-19T16:15:54.610Z'
                      tenant: tenant name
                      created_date: '2019-07-19T16:15:54.610Z'
                      updated_date: '2019-07-19T16:15:54.610Z'
      summary: Get All
      operationId: Get All
      description: Get all comments.
      tags:
      - Comments
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/comments/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Comments
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/comments/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Comments
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
