openapi: 3.2.0
info:
  title: YOOBIC Public Visits API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Visits
  description: Through this endpoint the details and/or the approval of the visit could be set.
paths:
  /public/api/visits/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  visit_id:
                    type: string
                  type:
                    type: string
                  description:
                    type: string
                  visit_date:
                    type: string
                  start_time:
                    type: string
                example:
                  visit_id: 54ab03c6546847ee0d30084a
                  type: stocktaking
                  description: scheduled store visit
                  visit_date: '2019-09-04T00:00:00.000Z'
                  start_time: '17:00'
              examples:
                response:
                  value:
                    visit_id: 54ab03c6546847ee0d30084a
                    type: stocktaking
                    description: scheduled store visit
                    visit_date: '2019-09-04T00:00:00.000Z'
                    start_time: '17:00'
      summary: Get
      operationId: Get
      description: Get a visit for the given id.
      tags:
      - Visits
      parameters:
      - name: id
        in: path
        description: The id of the visit
        required: true
        example: 54ab03c6546847ee0d30084a
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  visit_id:
                    type: string
                  type:
                    type: string
                  description:
                    type: string
                  user_id:
                    type: string
                  creator_id:
                    type: string
                  store_id:
                    type: string
                  visit_date:
                    type: string
                  start_time:
                    type: string
                  end_time:
                    type: string
                  compliant:
                    type: boolean
                example:
                  visit_id: 54ab03c6546847ee0d30084a
                  type: stocktaking
                  description: Approved store visit.
                  user_id: 5d160d2486191e003b3e538b
                  creator_id: 5d160d2486191e003b3e538b
                  store_id: 5d160a327411ab005c986216
                  visit_date: '2019-09-04T00:00:00.000Z'
                  start_time: '17:00'
                  end_time: '18:30'
                  compliant: true
              examples:
                response:
                  value:
                    visit_id: 54ab03c6546847ee0d30084a
                    type: stocktaking
                    description: Approved store visit.
                    user_id: 5d160d2486191e003b3e538b
                    creator_id: 5d160d2486191e003b3e538b
                    store_id: 5d160a327411ab005c986216
                    visit_date: '2019-09-04T00:00:00.000Z'
                    start_time: '17:00'
                    end_time: '18:30'
                    compliant: true
      summary: Partial Update
      operationId: Partial Update
      description: Update a subset of properties of a visit
      tags:
      - Visits
      parameters:
      - name: id
        in: path
        description: The id of the visit
        required: true
        example: 54ab03c6546847ee0d30084a
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/visits?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    visit_id:
                      type: string
                    type:
                      type: string
                    description:
                      type: string
                    user_id:
                      type: string
                    creator_id:
                      type: string
                    store_id:
                      type: string
                    visit_date:
                      type: string
                    start_time:
                      type: string
                    end_time:
                      type: string
                    compliant:
                      type: boolean
                    created_date:
                      type: string
                    updated_date:
                      type: string
                  required:
                  - visit_id
                  - type
                  - user_id
                  - creator_id
                  - store_id
                  - visit_date
                  - start_time
                  - end_time
                  - created_date
                  - updated_date
                example:
                - visit_id: 54ab03c6546847ee0d30084a
                  type: stocktaking
                  description: Approved store visit.
                  user_id: 5d160d2486191e003b3e538b
                  creator_id: 5aaf8a1bad9a1800354732bd
                  store_id: 5d160a327411ab005c986216
                  visit_date: '2019-09-04T00:00:00.000Z'
                  start_time: '17:00'
                  end_time: '18:30'
                  compliant: true
                  created_date: '2019-09-04T08:24:30.793Z'
                  updated_date: '2019-09-04T08:24:30.793Z'
                - visit_id: 5d4bdc3e1fca0e003b469a7f
                  type: stocktaking
                  user_id: 5d160d2486191e003b3e538b
                  creator_id: 5aaf8a1bad9a1800354732bd
                  store_id: 5ae065ec5d77d00035a6e9fb
                  visit_date: '2019-09-04T00:00:00.000Z'
                  start_time: '12:00'
                  end_time: '13:30'
                  created_date: '2019-09-04T08:24:30.793Z'
                  updated_date: '2019-09-04T08:24:30.793Z'
              examples:
                response:
                  value:
                  - visit_id: 54ab03c6546847ee0d30084a
                    type: stocktaking
                    description: Approved store visit.
                    user_id: 5d160d2486191e003b3e538b
                    creator_id: 5aaf8a1bad9a1800354732bd
                    store_id: 5d160a327411ab005c986216
                    visit_date: '2019-09-04T00:00:00.000Z'
                    start_time: '17:00'
                    end_time: '18:30'
                    compliant: true
                    created_date: '2019-09-04T08:24:30.793Z'
                    updated_date: '2019-09-04T08:24:30.793Z'
                  - visit_id: 5d4bdc3e1fca0e003b469a7f
                    type: stocktaking
                    user_id: 5d160d2486191e003b3e538b
                    creator_id: 5aaf8a1bad9a1800354732bd
                    store_id: 5ae065ec5d77d00035a6e9fb
                    visit_date: '2019-09-04T00:00:00.000Z'
                    start_time: '12:00'
                    end_time: '13:30'
                    created_date: '2019-09-04T08:24:30.793Z'
                    updated_date: '2019-09-04T08:24:30.793Z'
      summary: Get All
      operationId: Get All
      description: Get all the visits.
      tags:
      - Visits
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/visits/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Visits
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/visits:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            '*/*':
              schema:
                type: object
                properties:
                  visit_id:
                    type: string
                  user_id:
                    type: string
                  creator_id:
                    type: string
                  store_id:
                    type: string
                  visit_date:
                    type: string
                  group_ids:
                    type: array
                    items:
                      type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  visit_id: 5e38279864bc4e003a2b56e0
                  user_id: 53fb03c6546847ee0d30086a
                  creator_id: 5caf51463a4a9a00547953f8
                  store_id: 5739b18c6b8e2ac941fbee86
                  visit_date: '2020-01-28T00:00:00.000Z'
                  group_ids:
                  - test
                  created_date: '2020-02-03T14:00:56.976Z'
                  updated_date: '2020-02-03T14:00:56.976Z'
      summary: Create
      operationId: Create
      description: 'You may create a new single visit or multiple visits using this action.

        When creating a single visit the body contains a json object, when creating multiple visits the body contains an array of objects.

        **Warning: a maximum of 1000 items can be sent in a single request.**'
      tags:
      - Visits
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/visits/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Visits
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/visits/import?type={type}:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Import file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Import file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Import
      operationId: Import
      description: 'See the Import file section for more information.


        ### Fields


        | Field | Format | Required | Readonly | Description |

        |--------------------------------|--------------|:--------:|:--------:|-----------------|

        |`visit_id` | string | | x | Unique id of the visit |

        |`user_id` | string | x | | Unique id of the user who will visit the store |

        |`store_id` | string | x | | Unique id of the associated store |

        |`group_ids` | array | x | | Group ids that can see this visit |

        |`start_time` | string | x | | The scheduled time of the visit. Format is HH:mm |

        |`end_time` | string | | | The end time of the visit. Format is HH:mm |

        |`visit_date` | date | x | | The scheduled date of the visit. Format is YYYY-MM-DD |

        |`compliant` | boolean | | | The compliance of the visit as marked by an area manager: `true` if marked compliant, `false` if marked noncompliant |

        |`type` | string | | | Type of the visit chosen among a predefined list |

        |`creator_id` | string | | x | Unique id of the visit creator |

        |`description` | timestamp | | | Description of the visit |

        |`updated_date` | timestamp | | x | Visit''s last update date |

        |`created_date` | timestamp | | x | Visit''s creation date |'
      tags:
      - Visits
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: Content-Disposition
        in: header
        description: e.g. form-data; name="file"; filename="file.csv"
        required: false
        example: form-data; name="file"; filename="file.csv"
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ImportBody'
components:
  requestBodies:
    ImportBody:
      content:
        multipart/form-data, boundary=AaB03x:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
