openapi: 3.2.0
info:
  title: YOOBIC Public Jobs API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Jobs
  description: The Jobs endpoint allows you to query the status of your asynchronous jobs, whether they are queued, running, completed, or expired.
paths:
  /public/api/jobs/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
      summary: View Status of a Job
      operationId: View Status of a Job
      description: ''
      tags:
      - Jobs
      parameters:
      - name: id
        in: path
        description: The id of the job
        required: true
        example: 53fzs3c6546847ee0d33386a
        schema:
          type: string
      security:
      - oauth2: []
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
