openapi: 3.2.0
info:
  title: YOOBIC Public Photos API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Photos
  description: contains information about uploaded photos and photos taken as part of a mission and its relations to the mission.
paths:
  /public/api/photos/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo_id:
                    type: string
                  updated_date:
                    type: string
                  created_date:
                    type: string
                  mission_id:
                    type: string
                  campaign_id:
                    type: string
                  mission_data_id:
                    type: string
                  store_id:
                    type: string
                  title:
                    type: string
                  url:
                    type: string
                  markup_url:
                    type: string
                  question_id:
                    type: string
                  phash:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
                  short_desc:
                    type: string
                  entity_id:
                    type: string
                example:
                  photo_id: 54ab03c6546847ee0d30081d
                  updated_date: '2018-05-23T04:51:40.862Z'
                  created_date: '2018-05-23T04:51:40.862Z'
                  mission_id: 54ab03c6546847ee0d30081c
                  campaign_id: 54ab03c6546847ee0d30077a
                  mission_data_id: 54ab03c6546847ee0d300790
                  store_id: 54ab03c6546847ee0d30076a
                  title: Rocket ltd photo 1
                  url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                  markup_url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidg.jpg
                  question_id: 54ab03c6546847ee0d30072b
                  phash: 12a34b6cd6cb2134
                  tags:
                  - OK
                  short_desc: Mission
                  entity_id: 54ab03c6546847ee0d30072a
              examples:
                response:
                  value:
                    photo_id: 54ab03c6546847ee0d30081d
                    updated_date: '2018-05-23T04:51:40.862Z'
                    created_date: '2018-05-23T04:51:40.862Z'
                    mission_id: 54ab03c6546847ee0d30081c
                    campaign_id: 54ab03c6546847ee0d30077a
                    mission_data_id: 54ab03c6546847ee0d300790
                    store_id: 54ab03c6546847ee0d30076a
                    title: Rocket ltd photo 1
                    url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                    markup_url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidg.jpg
                    question_id: 54ab03c6546847ee0d30072b
                    phash: 12a34b6cd6cb2134
                    tags:
                    - OK
                    short_desc: Mission
                    entity_id: 54ab03c6546847ee0d30072a
      summary: Get
      operationId: Get
      description: Get a photo for the given id.
      tags:
      - Photos
      parameters:
      - name: id
        in: path
        description: The id of the photo
        required: true
        example: 54ab03c6546847ee0d30081d
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/photos:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo_id:
                    type: string
                  title:
                    type: string
                  url:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  photo_id: 5dc14612234f047cfe100a09
                  title: Shelf No. 1
                  url: https://res.cloudinary.com/www-yoobic-com/image/upload/v1572947475/qyrpyiscrd28s4hbrxqm.jpg
                  created_date: '2019-11-05T09:51:14.937Z'
                  updated_date: '2019-11-05T09:51:14.937Z'
              examples:
                response:
                  value:
                    photo_id: 5dc14612234f047cfe100a09
                    title: Shelf No. 1
                    url: https://res.cloudinary.com/www-yoobic-com/image/upload/v1572947475/qyrpyiscrd28s4hbrxqm.jpg
                    created_date: '2019-11-05T09:51:14.937Z'
                    updated_date: '2019-11-05T09:51:14.937Z'
      summary: Create
      operationId: Create
      description: 'Upload a photo.


        To upload a photo, you should make a post request of type `multipart/form-data`.

        The request body should contain two fields:


        `file`: the binary image file you want to upload.

        `title`: give a title to the photo.'
      tags:
      - Photos
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/photos?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    photo_id:
                      type: string
                    updated_date:
                      type: string
                    created_date:
                      type: string
                    mission_id:
                      type: string
                    campaign_id:
                      type: string
                    mission_data_id:
                      type: string
                    store_id:
                      type: string
                    title:
                      type: string
                    url:
                      type: string
                    markup_url:
                      type: string
                    question_id:
                      type: string
                    phash:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                    short_desc:
                      type: string
                    entity_id:
                      type: string
                  required:
                  - photo_id
                  - updated_date
                  - created_date
                  - mission_id
                  - campaign_id
                  - mission_data_id
                  - store_id
                  - title
                  - url
                  - question_id
                  - phash
                  - tags
                  - short_desc
                  - entity_id
                example:
                - photo_id: 54ab03c6546847ee0d30081d
                  updated_date: '2018-05-23T04:51:40.862Z'
                  created_date: '2018-05-23T04:51:40.862Z'
                  mission_id: 54ab03c6546847ee0d30081c
                  campaign_id: 54ab03c6546847ee0d30077a
                  mission_data_id: 54ab03c6546847ee0d300790
                  store_id: 54ab03c6546847ee0d30076a
                  title: Rocket ltd photo 1
                  url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                  markup_url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                  question_id: 54ab03c6546847ee0d30072b
                  phash: 12a34b6cd6cb2134
                  tags:
                  - OK
                  short_desc: Mission
                  entity_id: 54ab03c6546847ee0d30072a
                - photo_id: 54ab03c6546847ee0d30081e
                  updated_date: '2018-05-23T04:51:40.862Z'
                  created_date: '2018-05-23T04:51:40.862Z'
                  mission_id: 54ab03c6546847ee0d30081c
                  campaign_id: 54ab03c6546847ee0d30077a
                  mission_data_id: 54ab03c6546847ee0d300790
                  store_id: 54ab03c6546847ee0d30076a
                  title: Rocket ltd photo 2
                  url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                  question_id: 54ab03c6546847ee0d30072c
                  phash: 12a34b6cd6cb2134
                  tags:
                  - 'No'
                  short_desc: Mission
                  entity_id: 54ab03c6546847ee0d30072b
              examples:
                response:
                  value:
                  - photo_id: 54ab03c6546847ee0d30081d
                    updated_date: '2018-05-23T04:51:40.862Z'
                    created_date: '2018-05-23T04:51:40.862Z'
                    mission_id: 54ab03c6546847ee0d30081c
                    campaign_id: 54ab03c6546847ee0d30077a
                    mission_data_id: 54ab03c6546847ee0d300790
                    store_id: 54ab03c6546847ee0d30076a
                    title: Rocket ltd photo 1
                    url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                    markup_url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                    question_id: 54ab03c6546847ee0d30072b
                    phash: 12a34b6cd6cb2134
                    tags:
                    - OK
                    short_desc: Mission
                    entity_id: 54ab03c6546847ee0d30072a
                  - photo_id: 54ab03c6546847ee0d30081e
                    updated_date: '2018-05-23T04:51:40.862Z'
                    created_date: '2018-05-23T04:51:40.862Z'
                    mission_id: 54ab03c6546847ee0d30081c
                    campaign_id: 54ab03c6546847ee0d30077a
                    mission_data_id: 54ab03c6546847ee0d300790
                    store_id: 54ab03c6546847ee0d30076a
                    title: Rocket ltd photo 2
                    url: https://res.cloudinary.com/yoobic/image/upload/v1475779283/r4b1ticoyezzkdubkidf.jpg
                    question_id: 54ab03c6546847ee0d30072c
                    phash: 12a34b6cd6cb2134
                    tags:
                    - 'No'
                    short_desc: Mission
                    entity_id: 54ab03c6546847ee0d30072b
      summary: Get All
      operationId: Get All
      description: Get all the photos.
      tags:
      - Photos
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/photos/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Photos
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/photos/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Photos
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
