openapi: 3.2.0
info:
  title: YOOBIC Public Communities API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Communities
  description: Communities are a sub-section of the general Newsfeed tab in YOOBIC.
paths:
  /public/api/communities/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  community_id:
                    type: string
                  name:
                    type: string
                  creator_id:
                    type: string
                  type:
                    type: string
                  audience_id:
                    type: string
                  allow_posts_from_all:
                    type: boolean
                  disable_notifications:
                    type: boolean
                  hide_posts_from_newsfeed:
                    type: boolean
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  community_id: 668d495b335f79001d10cfd7
                  name: Public API community
                  creator_id: 662a0acf7495703637e9c884
                  type: open
                  audience_id: 668d22072e701b001dec95bb
                  allow_posts_from_all: true
                  disable_notifications: false
                  hide_posts_from_newsfeed: false
                  created_date: '2024-07-09T14:29:47.747Z'
                  updated_date: '2025-01-07T12:55:09.085Z'
              examples:
                response:
                  value:
                    community_id: 668d495b335f79001d10cfd7
                    name: Public API community
                    creator_id: 662a0acf7495703637e9c884
                    type: open
                    audience_id: 668d22072e701b001dec95bb
                    allow_posts_from_all: true
                    disable_notifications: false
                    hide_posts_from_newsfeed: false
                    created_date: '2024-07-09T14:29:47.747Z'
                    updated_date: '2025-01-07T12:55:09.085Z'
      summary: Get
      operationId: Get
      description: Get a community for the given id.
      tags:
      - Communities
      parameters:
      - name: id
        in: path
        description: The id of the community
        required: true
        example: 668d495b335f79001d10cfd7
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/communities?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Get all communitites
      operationId: Get all communitites
      description: Get all communities.
      tags:
      - Communities
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{"where": {"audience_id": "668d22072e701b001dec95bb"}}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/communities:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    community_id:
                      type: string
                    name:
                      type: string
                    creator_id:
                      type: string
                    type:
                      type: string
                    audience_id:
                      type: string
                    allow_posts_from_all:
                      type: boolean
                    disable_notifications:
                      type: boolean
                    hide_posts_from_newsfeed:
                      type: boolean
                    created_date:
                      type: string
                    updated_date:
                      type: string
                example:
                - community_id: 677e40f690f4a601c4bf8735
                  name: NEW Test Community
                  creator_id: 662a0acf7495703637e9c884
                  type: open
                  audience_id: 668d22072e701b001dec95bb
                  allow_posts_from_all: true
                  disable_notifications: false
                  hide_posts_from_newsfeed: false
                  created_date: '2025-01-08T09:10:14.603Z'
                  updated_date: '2025-01-08T09:10:14.603Z'
              examples:
                response:
                  value:
                  - community_id: 677e40f690f4a601c4bf8735
                    name: NEW Test Community
                    creator_id: 662a0acf7495703637e9c884
                    type: open
                    audience_id: 668d22072e701b001dec95bb
                    allow_posts_from_all: true
                    disable_notifications: false
                    hide_posts_from_newsfeed: false
                    created_date: '2025-01-08T09:10:14.603Z'
                    updated_date: '2025-01-08T09:10:14.603Z'
      summary: Create
      operationId: Create
      description: Create a community
      tags:
      - Communities
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                audience_id:
                  type: string
                allow_posts_from_all:
                  type: boolean
                disable_notifications:
                  type: boolean
                hide_posts_from_newsfeed:
                  type: boolean
              example:
                name: NEW Test Community
                type: open
                audience_id: 668d22072e701b001dec95bb
                allow_posts_from_all: true
                disable_notifications: false
                hide_posts_from_newsfeed: false
      security:
      - oauth2: []
  /public/api/communities/{community_id}/promote_manager/{manager_id}:
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 662a4534fb6cd214b1fab989 is now a manager of 668d495b335f79001d10cfd7 community
              examples:
                response:
                  value:
                    message: 662a4534fb6cd214b1fab989 is now a manager of 668d495b335f79001d10cfd7 community
      summary: Nominate a community manager
      operationId: Nominate a community manager
      description: Nominate the manager of a community
      tags:
      - Communities
      parameters:
      - name: community_id
        in: path
        description: The id of the community
        required: true
        example: 668d495b335f79001d10cfd7
        schema:
          type: string
      - name: manager_id
        in: path
        description: The id of the manager
        required: true
        example: 662a4534fb6cd214b1fab989
        schema:
          type: string
  /public/api/communities/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Communities
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/communities/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Communities
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
