openapi: 3.2.0
info:
  title: YOOBIC Public Store Types API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Store Types
  description: Stores always belong to specific Store Type.
paths:
  /public/api/store-types/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  store_type_id:
                    type: string
                  name:
                    type: string
                  group_ids:
                    type: array
                    items:
                      type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  store_type_id: 56b0c262e9a22a4e5f02be7d
                  name: ice-cream
                  group_ids:
                  - managers
                  created_date: '2016-02-02T14:51:14.644Z'
                  updated_date: '2016-07-15T14:18:41.750Z'
              examples:
                response:
                  value:
                    store_type_id: 56b0c262e9a22a4e5f02be7d
                    name: ice-cream
                    group_ids:
                    - managers
                    created_date: '2016-02-02T14:51:14.644Z'
                    updated_date: '2016-07-15T14:18:41.750Z'
      summary: Get
      operationId: Get
      description: Get a store type for the given id.
      tags:
      - Store Types
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
      summary: Delete
      operationId: Delete
      description: Delete a store type by id.
      tags:
      - Store Types
      security:
      - oauth2: []
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  store_type_id:
                    type: string
                  name:
                    type: string
                  group_ids:
                    type: array
                    items:
                      type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  store_type_id: 56b0c262e9a22a4e5f02be7d
                  name: ice-cream
                  group_ids:
                  - managers
                  created_date: '2016-02-02T14:51:14.644Z'
                  updated_date: '2016-07-15T14:18:41.750Z'
              examples:
                response:
                  value:
                    store_type_id: 56b0c262e9a22a4e5f02be7d
                    name: ice-cream
                    group_ids:
                    - managers
                    created_date: '2016-02-02T14:51:14.644Z'
                    updated_date: '2016-07-15T14:18:41.750Z'
      summary: Partial Update
      operationId: Partial Update
      description: Update a subset of properties of a store type
      tags:
      - Store Types
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              example:
                name: ice-cream
      security:
      - oauth2: []
  /public/api/store-types?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        store_type_id:
                          type: string
                        name:
                          type: string
                        group_ids:
                          type: array
                          items:
                            type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - store_type_id
                      - name
                      - group_ids
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - store_type_id: 56b0c262e9a22a4e5f02be7d
                    name: ice-cream
                    group_ids:
                    - managers
                    created_date: '2016-02-02T14:51:14.644Z'
                    updated_date: '2016-07-15T14:18:41.750Z'
                  - store_type_id: 56b0c262e9a22a4e5f02be7e
                    name: fruit
                    group_ids:
                    - staf
                    - managers
                    created_date: '2016-02-02T14:51:14.644Z'
                    updated_date: '2016-07-15T14:18:41.750Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - store_type_id: 56b0c262e9a22a4e5f02be7d
                      name: ice-cream
                      group_ids:
                      - managers
                      created_date: '2016-02-02T14:51:14.644Z'
                      updated_date: '2016-07-15T14:18:41.750Z'
                    - store_type_id: 56b0c262e9a22a4e5f02be7e
                      name: fruit
                      group_ids:
                      - staf
                      - managers
                      created_date: '2016-02-02T14:51:14.644Z'
                      updated_date: '2016-07-15T14:18:41.750Z'
      summary: Get all
      operationId: Get all
      description: Get all stores.
      tags:
      - Store Types
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/store-types/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Store Types
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/store-types:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    store_type_id:
                      type: string
                    name:
                      type: string
                    group_ids:
                      type: array
                      items:
                        type: string
                    created_date:
                      type: string
                    updated_date:
                      type: string
                  required:
                  - store_type_id
                  - name
                  - group_ids
                  - created_date
                  - updated_date
                example:
                - store_type_id: 56b0c262e9a22a4e5f02be7d
                  name: ice-cream
                  group_ids:
                  - managers
                  created_date: '2016-02-02T14:51:14.644Z'
                  updated_date: '2016-07-15T14:18:41.750Z'
                - store_type_id: 56b0c262e9a22a4e5f02be7e
                  name: fruit
                  group_ids:
                  - managers
                  - staf
                  created_date: '2016-02-02T14:51:14.644Z'
                  updated_date: '2016-07-15T14:18:41.750Z'
              examples:
                response:
                  value:
                  - store_type_id: 56b0c262e9a22a4e5f02be7d
                    name: ice-cream
                    group_ids:
                    - managers
                    created_date: '2016-02-02T14:51:14.644Z'
                    updated_date: '2016-07-15T14:18:41.750Z'
                  - store_type_id: 56b0c262e9a22a4e5f02be7e
                    name: fruit
                    group_ids:
                    - managers
                    - staf
                    created_date: '2016-02-02T14:51:14.644Z'
                    updated_date: '2016-07-15T14:18:41.750Z'
      summary: Create
      operationId: Create
      description: 'You may create a new single store type or multiple store types using this action.

        When creating a single store type, the body contains a json object, when creating multiple store types, the body contains an array of objects.

        **Warning: a maximum of 1000 items can be sent in a single request.**'
      tags:
      - Store Types
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                group_ids:
                  type: array
                  items:
                    type: string
              example:
                name: ice-cream
                group_ids:
                - managers
      security:
      - oauth2: []
  /public/api/store-types/export?{filter}&type={type}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Store Types
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/store-types/import?type={type}:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Import file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Import file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Import
      operationId: Import
      description: 'See the Import file section for more information.


        ### Fields


        | Field | Format | Required | Description |

        |--------------------------|---------|:--------:|------------------|

        |`store_type_id` | string | | Unique store type id |

        |`name` | string | x | Name of the store type|

        |`group_ids` | array | x | Group ids that can see this store type|'
      tags:
      - Store Types
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: Content-Disposition
        in: header
        description: e.g. form-data; name="file"; filename="file.csv"
        required: false
        example: form-data; name="file"; filename="file.csv"
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ImportBody'
components:
  requestBodies:
    ImportBody:
      content:
        multipart/form-data, boundary=AaB03x:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
