openapi: 3.2.0
info:
  title: YOOBIC Public Chats API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Chats
  description: 'Chats are used for internal communication between users directly in the YOOBIC app.


    ### Fields


    | Field | Type | Required | Readonly | OrderBy | Description |

    |-------|:----:|:--------:|:--------:|:-------:|-------------|

    |`sender_id`| string | x | | | Unique id of the user account from which the message is sent |

    |`recipient_id`| string | x | | | Unique id of the user that will receive the message |

    |`text`| string | x | | | Text of the message |

    |`attachments`| file | | | | File link |'
paths:
  /public/api/chats:
    post:
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  sender_id:
                    type: string
                  recipient_id:
                    type: string
                  text:
                    type: string
                  attachments:
                    type: string
                  created_date:
                    type: string
                example:
                  sender_id: 54ab03c6546847ee0d30086a
                  recipient_id: 54ab03c6546847ee0d30086b
                  text: Hello, how are you?
                  attachments: https://assets.yoobic.com/image/upload/v1/file.jpg
                  created_date: '2025-12-29T10:00:00.000Z'
              examples:
                response:
                  value:
                    sender_id: 54ab03c6546847ee0d30086a
                    recipient_id: 54ab03c6546847ee0d30086b
                    text: Hello, how are you?
                    attachments: https://assets.yoobic.com/image/upload/v1/file.jpg
                    created_date: '2025-12-29T10:00:00.000Z'
      summary: Create
      operationId: Create
      description: Send a chat message from a user to another user.
      tags:
      - Chats
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: string
                recipient_id:
                  type: string
                text:
                  type: string
                attachments:
                  type: string
              example:
                sender_id: 54ab03c6546847ee0d30086a
                recipient_id: 54ab03c6546847ee0d30086b
                text: Hello, how are you?
                attachments: https://assets.yoobic.com/image/upload/v1/file.jpg
      security:
      - oauth2: []
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
