openapi: 3.2.0
info:
  title: YOOBIC Public Badges API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Badges
  description: A badge is a customized reward earned by a learner after completing a lesson.
paths:
  /public/api/badges/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  badge_id:
                    type: string
                  creator_id:
                    type: string
                  title:
                    type: string
                  icon:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  badge_id: 61b9b435c8f864003a552378
                  creator_id: 61af7b01ee30bd0025145674
                  title: woohoo
                  icon: award-trophy-star
                  created_date: '2021-12-15T09:24:05.652Z'
                  updated_date: '2021-12-15T09:24:05.652Z'
              examples:
                response:
                  value:
                    badge_id: 61b9b435c8f864003a552378
                    creator_id: 61af7b01ee30bd0025145674
                    title: woohoo
                    icon: award-trophy-star
                    created_date: '2021-12-15T09:24:05.652Z'
                    updated_date: '2021-12-15T09:24:05.652Z'
      summary: Get
      operationId: Get
      description: Get a badge for the given id.
      tags:
      - Badges
      parameters:
      - name: id
        in: path
        description: The id of the badge
        required: true
        example: 61b9b435c8f864003a552378
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/badges?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        badge_id:
                          type: string
                        creator_id:
                          type: string
                        title:
                          type: string
                        icon:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - badge_id
                      - creator_id
                      - title
                      - icon
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - badge_id: 61b8de5b55c2d5002449ab27
                    creator_id: 61af7b01ee30bd0025145674
                    title: doc lesson
                    icon: folder-add
                    created_date: '2021-12-14T18:11:39.026Z'
                    updated_date: '2021-12-14T18:11:39.026Z'
                  - badge_id: 61a622f2a9accb0024ea732b
                    creator_id: 6194baa5aedfd900296e744f
                    title: Yoobic Master
                    icon: automotive-airplane
                    created_date: '2021-11-30T13:11:14.247Z'
                    updated_date: '2021-11-30T13:11:14.247Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - badge_id: 61b8de5b55c2d5002449ab27
                      creator_id: 61af7b01ee30bd0025145674
                      title: doc lesson
                      icon: folder-add
                      created_date: '2021-12-14T18:11:39.026Z'
                      updated_date: '2021-12-14T18:11:39.026Z'
                    - badge_id: 61a622f2a9accb0024ea732b
                      creator_id: 6194baa5aedfd900296e744f
                      title: Yoobic Master
                      icon: automotive-airplane
                      created_date: '2021-11-30T13:11:14.247Z'
                      updated_date: '2021-11-30T13:11:14.247Z'
      summary: Get All
      operationId: Get All
      description: Get all the badges.
      tags:
      - Badges
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/badges/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Badges
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/badges/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Badges
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
